### ISSUE TITLE
add 'columns' key to config

### ISSUE THREAD

**Issue by tacman** [survos/SurvosPixieBundle#2]
We need to require some column creation, not just match the csv / json column names.

```yaml
tables:
   person:
       columns:
             - name: ageAtDeath
               calc: deathYear - birthYear
       
```
